{% set name = "confection" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4fec47190057c43c9acbecb8b1b87a9bf31c469caa0d6888a5b9384432fdba5a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<1.10.0
    - typing_extensions >=3.7.4.1,<4.2.0  # [py<=37]
    - srsly >=2.4.0,<3.0.0

test:
  imports:
    - {{ name }}
  requires:
    - pytest
    # TODO: reenable after the test suite is updated
    #- numpy
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}


about:
  home: https://github.com/explosion/confection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The sweetest config system for Python
  description: |
    A lightweight library that offers a configuration system letting you
    conveniently describe arbitrary trees of objects.
  doc_url: https://github.com/explosion/confection
  dev_url: https://github.com/explosion/confection

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
