{% set name = "confection" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1ddf5885da635f0e260a40b339730806dfb1bd17d30e08764f35af841b04ecf

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<1.11.0
    - typing_extensions >=3.7.4.1,<4.5.0  # [py<38]
    - srsly >=2.4.0,<3.0.0

test:
  imports:
    - {{ name }}
  requires:
    - pytest >=5.2.0,!=7.1.0
    - numpy
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/confection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The sweetest config system for Python
  description: |
    A lightweight library that offers a configuration system letting you
    conveniently describe arbitrary trees of objects.
  doc_url: https://github.com/explosion/confection
  dev_url: https://github.com/explosion/confection

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
